#!/bin/bash

echo $1

rm -Rf video_frames
mkdir -p video_frames
mkdir -p processed_frames

avconv -i "$1" -vn -acodec copy video_soundtrack.aac
avconv -i "$1" -r 29.92 -f image2 video_frames/frame_%04d.png 
